- name: message-1
  ansible.builtin.degbug:
    msg: "Hi Message From 1 "

- name: message-2
  ansible.builtin.debug:
    msg: "Hi Message From 2 "

- name: message-3
  ansible.builtin.debug:
    msg: "Hi Message From 3 "